export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_TOKEN = "SET_CURRENT_TOKEN";
export const LOGOUT = "LOGOUT";
export const LOGIN = "LOGIN";
export const UPDATE_FAILED_LOGIN = "UPDATE_FAILED_LOGIN";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const SET_CURRENT_COUNTER = "SET_CURRENT_COUNTER";
export const RESET_FAILED_COUNTER = "RESET_FAILED_COUNTER";
